const yaku = [
  'menzentsumo',
  'riichi',
  'ippatsu',
  'chankan',
  'rinshan',
  'haitei',
  'houtei',
  'pinfu',
  'tanyao',
  'iipeikou',
  'own wind east',
  'own wind south',
  'own wind west',
  'own wind north',
  'round wind east',
  'round wind south',
  'round wind west',
  'round wind north',
  'haku',
  'hatsu',
  'chun',
  'daburu riichi',
  'chiitoitsu',
  'chanta',
  'ittsu',
  'sanshoku',
  'sanshoku doukou',
  'sankantsu',
  'toitoi',
  'sanankou',
  'shosangen',
  'honroutou',
  'ryanpeikou',
  'junchan',
  'honitsu',
  'chinitsu',
  'renhou',
  'tenhou',
  'chihou',
  'daisangen',
  'suuankou',
  'suuankou tanki',
  'tsuuiisou',
  'ryuuiisou',
  'chinroutou',
  'chuurenpoto',
  'chuurenpoto 9 sides',
  'kokushimusou',
  'kokushimusou 13 sides',
  'daisuushi',
  'shosuushi',
  'suukantsu',
  'dora',
  'uradora',
  'akadora',
]
